# Generated by Django 4.0.2 on 2022-04-13 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_product_brand_remove_product_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='vendor',
        ),
    ]
