# Generated by Django 4.0.2 on 2022-03-21 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
    ]
