# Generated by Django 4.0.2 on 2022-03-21 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_category_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
