# Generated by Django 4.0.2 on 2022-03-22 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default='Default-Category', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='base.category'),
        ),
    ]
