# Generated by Django 4.0.2 on 2022-03-22 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_category_options_alter_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
