# Generated by Django 4.0.2 on 2022-03-25 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default='Default-Category', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='base.category'),
        ),
    ]
